language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install: "pip install -r requirements.txt"
before_script:
  - python manage.py migrate
  - python manage.py runserver
script:
  - flake8
  - python manage.py test
