# Generated by Django 2.2.6 on 2019-11-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='agent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Agent'),
            preserve_default=False,
        ),
    ]
