# Generated by Django 2.2.6 on 2019-10-29 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errors',
            name='active',
            field=models.CharField(default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='errors',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='errors',
            name='events',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='errors',
            name='log',
            field=models.CharField(default='Erro no 127.0.0.1', max_length=200),
            preserve_default=False,
        ),
    ]
