# Generated by Django 2.2.6 on 2019-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191029_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errors',
            name='active',
        ),
        migrations.AddField(
            model_name='errors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
