# Generated by Django 2.2.6 on 2019-11-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_error_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Agent'),
        ),
    ]
