# Generated by Django 2.2.6 on 2019-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191102_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='env',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
