# Generated by Django 2.2.5 on 2019-10-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191016_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='level',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING')], default='ERROR', max_length=32),
        ),
    ]
