# Generated by Django 2.2.6 on 2019-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191108_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
