# Generated by Django 2.2.6 on 2019-11-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191108_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
